CREATE TABLE `data`.`data` (
  `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `GENDER` VARCHAR(45) NOT NULL,
  `AGE` VARCHAR(45) NOT NULL,
  `PAYMENT_METHOD` VARCHAR(45) NOT NULL,
  `CHURN` VARCHAR(45) NOT NULL,
  `LAST_TRANSACTION` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`)
)
ENGINE = InnoDB;